# Generated by Django 3.0.1 on 2019-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_UserName', models.CharField(max_length=200, verbose_name='имя пользователья')),
                ('registration_UserPhone', models.IntegerField(verbose_name='номер пользователья')),
                ('reg_date', models.DateTimeField(verbose_name='дата регистрации')),
            ],
        ),
    ]
